server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret: 
          facebook:
            client-id: 
            client-secret: 
          google:
            client-id: 
            client-secret: 
